CREATE DATABASE kunkunchatroom;
USE kunkunchatroom;
CREATE TABLE USER(
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20),
	PASSWORD VARCHAR(20),
	TYPE VARCHAR(20)
);

INSERT INTO USER VALUES (NULL,'kunkun','kunkun','admin');
INSERT INTO USER VALUES (NULL,'111','111','user');
INSERT INTO USER VALUES (NULL,'kun','kun','admin');
INSERT INTO USER VALUES (NULL,'222','222','user');